export const projects = [
  {
    title: 'Flask E-commerce Website',
    description: "This is a ecommerce website build using flask a python webfreamwork. In which user can search product get a detailed page for product and can give review on product. User can login and signup with otp authentication as well as can change password using otp which they will get on there email.",
    image:'/images/7.png',
    alt:'flask-ecommerce',
    tags:['Flask','HTML', 'CSS', 'Javascript', 'Razopay'],
    source:'https://shivvvuu.pythonanywhere.com/',
    visit:'https://shivvvuu.pythonanywhere.com/',
    id:0
  },
  {
    title: 'MERN AI-Image',
    description: "Using Vite, Node.js, Express & MongoDB full-stack website is build. The App is called DALL-E 2.0 and it helps user to get an AI- generated image and share with community.",
      image:'/images/1.png',
      alt: 'mern-ai-img',
      tags: ['MongoDB', 'Express', 'React', 'Node','OpenAI'],
    source: 'https://github.com/shivvvuu/MERN_AI_IMG',
    visit: 'https://imagebyai.netlify.app/',
    id: 1,
  },
  {
    title: 'YouTube Clone',
    description:"This is Youtube clone build using ReactJS it's the front-end which is connected to YouTube by RapidAI where user can browse and watch youtube videos.  ",
    image:'/images/2.png',
    alt:'youtube-clone',
    tags: ['React', 'RapidAPI'],
    source: 'https://github.com/shivvvuu/Modern_YouTube_Clone',
    visit: 'https://youtube-clone-by-shivamjhod.netlify.app/',
    id: 2,
  },
  {
    title: 'AI-ChatGPT App',
    description: "This is Chat-bot app build using ChatGPT(OpenAI Product) and Vite framework for front-end and nodejs for backend .",
      image: '/images/3.png',
      alt:'ai-chatgpt',
      tags: ['Vite', 'NodeJS', 'OpenAI'],
    source: 'https://github.com/shivvvuu/Open_AI',
    visit: 'https://open-ai-ruby.vercel.app/',
    id: 3,
  },
  {
    title: 'Portfolio',
    description: "This is a code for my portfolio. This app is build by NEXTJS and tailwind for better user experience An host on AWS amplify.",
    image: '/images/4.png',
    alt:'portfolio',
    tags: ['NextJS', 'AWS', 'Tailwind'],
    source: 'https://github.com/shivvvuu/NextJS',
    visit: '/',
    id: 4,
  },
  {
    title: 'Obect-Detection',
    description: "This is a code for Object-Detection. This app is build using Tensorflow , anaconda, python, jupyter notebook for detecting environment objects.(Ongoing)",
    image: '/images/5.png',
    alt:'object-detection',
    tags: ['Tensorflow',  'anaconda'],
    source: 'https://github.com/shivvvuu/Tensorflow-Object-Detaction',
    id: 5,
  },
  {
    title: 'Signal Clone',
    description: "This is a code for Signal Clone APK. This app is build using React-Native, AWS for smooth experience.User can chat in real time.(Ongoing)",
    image: '/images/6.png',
    alt:'signal-clone',
    tags: ['React-Native', 'AWS', 'Type-Script'],
    source: 'https://github.com/shivvvuu/Signal/tree/master/signalclone',
    id: 6,
  },

];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey with C++', },
  { year: 2020, text: 'Worked as a freelance developer', },
  { year: 2021, text: 'Learnt JavaScript and Database ', },
  { year: 2022, text: 'Internship At Absolute Compliance', },
  { year: 2023, text: 'Adding new things...', },
];
